[package]
name = "inputshare-server"
version = "0.1.0"
authors = ["sidit77 <sidit77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
# pico-args = "0.4.1"
# inputshare-common = { path = "../inputshare-common" }
mio = {version = "0.8.0", features = ["os-poll", "net"]}