[package]
name = "inputshare-server"
version = "0.1.0"
authors = ["sidit77 <sidit77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
# pico-args = "0.4.1"
inputshare-common = { path = "../inputshare-common" }
mio = {version = "0.8", features = ["os-poll", "net"]}
mio-signals = "0.2.0"
udp_connections = {git = "https://github.com/sidit77/udp_connections.git"}
byteorder = "1"
vec_map = "0.8.2"