host_address = 'raspberrypi.local:60067'
hotkey = 'Apps'
backlist = [
    'VolumeDown',
    'VolumeUp',
    'VolumeMute',
    'MediaStop',
    'MediaPrevTrack',
    'MediaPlayPause',
    'MediaNextTrack',
]
