[package]
name = "inputshare-client"
version = "0.1.0"
authors = ["sidit77 <sidit77@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
winapi = { version = "0.3", features = ["winuser", "minwindef"] }
byteorder = "1"
anyhow = "1.0"
native-windows-gui = "1.0"
native-windows-derive = "1.0"
inputshare-common = { path = "../inputshare-common" }
winsock2_extensions = { path = "../lib/winsock2_extensions" }
yawi = {path = "../lib/yawi", features = ["serde"]}
udp_connections = {git = "https://github.com/sidit77/udp_connections.git"}


[target.'cfg(windows)'.build-dependencies]
winres = "0.1"