[package]
name = "inputshare-client"
version = "0.1.0"
authors = ["sidit77 <sidit77@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# confy = "0.4"
# serde = { version = "1.0", features = ["derive"] }
# pico-args = "0.4"
anyhow = "1.0"
# bitflags = "1.2"
# byteorder = "1.4"
# ctrlc = "3.1"
# mio = "0.6"
# mio-extras = "2.0"
# console = "0.14.1"
# yawi = { path = "../yawi", features = ["serde"] }
inputshare-common = { path = "../inputshare-common" }
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "windef", "minwindef", "basetsd", "processthreadsapi", "errhandlingapi", "winsock2", "wincon"] }
ctrlc = "3.2"
winsock2_extensions = { path = "../lib/winsock2_extensions" }
yawi = {path = "../lib/yawi"}
udp_connections = {git = "https://github.com/sidit77/udp_connections.git"}
byteorder = "1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"