[package]
name = "inputshare-client"
version = "2.3.0"
authors = ["sidit77 <sidit77@gmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.10"
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
# winapi = { version = "0.3", features = ["winuser", "minwindef"] }
# byteorder = "1"
anyhow = { version = "1.0", features = ["backtrace"] }
# native-windows-gui = "1.0"
# native-windows-derive = "1.0"

egui = "0.21"
winit = "0.28"

# inputshare-common = { path = "../lib/inputshare-common" }
# winsock2_extensions = { path = "../lib/winsock2_extensions" }
# yawi = {path = "../lib/yawi", features = ["serde"]}
egui-d3d11 = { path = "../lib/egui-d3d11", features = ["egui-winit"]}

udp_connections = {git = "https://github.com/sidit77/udp_connections.git"}
error-tools = { git = "https://github.com/sidit77/error-tools.git", features = ["log", "gui"] }

[build-dependencies]
tauri-winres = "0.1"