[package]
name = "inputshare-client"
version = "0.1.0"
authors = ["sidit77 <sidit77@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confy = "0.4"
serde = { version = "1.0", features = ["derive"] }
pico-args = "0.4"
anyhow = "1.0"
bitflags = "1.2"
byteorder = "1.4"
ctrlc = "3.1"
yawi = { path = "../yawi", features = ["serde"] }
inputshare-common = { path = "../inputshare-common" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"