[package]
name = "inputshare-client"
version = "0.1.0"
authors = ["sidit77 <sidit77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
laminar = "0.4.0"
anyhow = "1.0.40"
bitflags = "1.2.1"
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "windef", "minwindef"] }
native-windows-gui = "1.0.11"
