[package]
name = "inputshare-client"
version = "0.1.0"
authors = ["sidit77 <sidit77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confy = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
bitflags = "1.2.1"
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "windef", "minwindef", "basetsd"] }
native-windows-gui = "1.0.11"
